### ISSUE TITLE
Does Roboblender work with multibindings?

### ISSUE THREAD

**Issue by b4rd** [roboguice/roboguice#275]
The error I'm getting at startup:

```
java.lang.RuntimeException: Unable to create application mypackage.TestApplication: com.google.inject.CreationException: Unable to create injector, see the following errors:
    1) Error in custom provider, java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.Map.size()' on a null object reference
            at mypackage.DefaultConfigModule.configureCache(DefaultConfigModule.java:300) (via modules: mypackage.ProductionModule -> mypackage.DefaultConfigModule -> com.google.inject.multibindings.MapBinder$RealMapBinder)
    while locating java.util.Map<mypackage.cache.CacheAttributes, mypackage.cache.Cache>
    for field at mypackage.cache.DefaultCacheManager.cacheMap(Unknown Source)
            at mypackage.cache.DefaultCacheManager.class(Unknown Source)
    while locating mypackage.cache.DefaultCacheManager
    while locating mypackage.cache.CacheManager
    for field at mypackage.sendmoney.SendMoneyHelper.testCache(Unknown Source)

```

I rebuilt guice to print out the actual error, which is:

```
java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.Map.size()' on a null object reference
 at java.util.LinkedHashMap.<init>(LinkedHashMap.java:132)
 at com.google.inject.multibindings.MapBinder$RealMapBinder$RealMapProvider.get(MapBinder.java:544)
 at com.google.inject.multibindings.MapBinder$RealMapBinder$RealMapProvider.get(MapBinder.java:529)
 at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
 at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:54)
 at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:66)
 at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:46)
 at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:54)
 at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:132)
 at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:117)
 at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:88)
 at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:269)
 at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
 at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1066)
 at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
 at com.google.inject.Scopes$1$1.get(Scopes.java:65)
 at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
 at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
 at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:54)
 at com.google.inject.internal.InjectionRequestProcessor$StaticInjection$1.call(InjectionRequestProcessor.java:123)
 at com.google.inject.internal.InjectionRequestProcessor$StaticInjection$1.call(InjectionRequestProcessor.java:117)
 at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1059)
 at com.google.inject.internal.InjectionRequestProcessor$StaticInjection.injectMembers(InjectionRequestProcessor.java:117)
 at com.google.inject.internal.InjectionRequestProcessor.injectMembers(InjectionRequestProcessor.java:79)
 at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:171)
 at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
 at com.google.inject.Guice.createInjector(Guice.java:100)
 at com.google.inject.Guice.createInjector(Guice.java:87)
 at roboguice.RoboGuice.createGuiceInjector(RoboGuice.java:186)
 at roboguice.RoboGuice.getOrCreateBaseApplicationInjector(RoboGuice.java:114)
 at ...
```

The same configuration works well without Roboblender.
I couldn't figure out yet where this go wrong.

**Comment by TomRK1089** [comment]
I'm using RoboGuice successfully with both assisted inject and multibindings (using Maven, not Gradle). What I did was to exclude the regular Guice dependency from the two extensions using Maven's <exclusions> element. I assume Gradle has a similar configuration.

**Comment by richardradics** [comment]
So what is the answer for the question. Does roboblender work with multibindings? I get the same exception when I want to use it.
Thanks in advance!
