### ISSUE TITLE
Could not find a suitable constructor in roboguice.d.x. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.

### ISSUE THREAD

**Issue by huangsanm** [roboguice/roboguice#284]
hi，I used roboguice "compile 'org.roboguice:roboguice:3.+' "  , My project which added proguard .
it happen this when i open my App, I look roboguice'wiki and using here code "https://gist.github.com/matthawley/1327908" ,but don't work
can you help me!

```bash
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xmyunyou.bbbuy/com.xmyunyou.bbbuy.ui.WelcomActivity}: com.google.inject.CreationException: Unable to create injector, see the following errors:
    1) Could not find a suitable constructor in roboguice.d.x. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
            at roboguice.d.x.class(Unknown Source)
            at roboguice.a.a.configure(Unknown Source)
    1 error
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2305)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2359)
            at android.app.ActivityThread.access$700(ActivityThread.java:165)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1326)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5455)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1187)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:
    1) Could not find a suitable constructor in roboguice.d.x. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
            at roboguice.d.x.class(Unknown Source)
            at roboguice.a.a.configure(Unknown Source)
    1 error
            at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Unknown Source)
            at com.google.inject.internal.InternalInjectorCreator.initializeStatically(Unknown Source)
            at com.google.inject.internal.InternalInjectorCreator.build(Unknown Source)
            at com.google.inject.Guice.createInjector(Unknown Source)
            at com.google.inject.Guice.createInjector(Unknown Source)
            at roboguice.a.a(Unknown Source)
            at roboguice.a.a(Unknown Source)
            at roboguice.a.a(Unknown Source)
            at roboguice.a.a(Unknown Source)
            at roboguie.activity.RoboFragmentActivity.onCreate(Unknown Source)
            at com.xmyunyou.bbbuy.utils.BaseActivity.onCreate(Unknown Source)
            at com.xmyunyou.bbbuy.ui.WelcomActivity.onCreate(Unknown Source)
            at android.app.Activity.performCreate(Activity.java:5372)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2267)
            ... 11 more
```

**Comment by stephanenicolas** [comment]
Please refer to the wiki for instructions on how to setup proguard for RG. It is not a beginners setup, proguard is not easy and may requires additional reading (stack over flow, instruction manual, etc.).
