### ISSUE TITLE
Roboguice strategy pattern getting named instances

### ISSUE THREAD

**Issue by ahmednasir91** [roboguice/roboguice#293]
I have `GCMMessage` interface that have many implementations like `BookingGCMMessage`, `CancelGCMMessage`. In the Roboguice module class I have defined Bindings like this

```
bind(GCMMessage.class).annotatedWith(Names.named("BOOKING")).to(BookingGCMMessage.class);
bind(GCMMessage.class).annotatedWith(Names.named("CANCEL")).to(CancelGCMMessage.class);
bind(GCMMessage.class).annotatedWith(Names.named("UPDATE")).to(UpdateGCMMessage.class);
```

In the class I am trying to get the instance like this,

```
    Injector injector = RoboGuice.getInjector(this);
    GCMMessage gcmMessage = injector.getInstance(Key.get(GCMMessage.class, Names.named("BOOKING")));
```

But the binding is not working and getting 

```
com.google.inject.ConfigurationException: Guice configuration errors:
    1) No implementation for com.app.dispatch.GCMMessage annotated with @com.google.inject.name.Named(value=BOOKING) was bound.
    while locating com.app.dispatch.GCMMessage annotated with @com.google.inject.name.Named(value=BOOKING)
    1 error
            at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1035) ~[na:0.0]
            at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1040) ~[na:0.0]
            at roboguice.inject.ContextScopedRoboInjector.getInstance(ContextScopedRoboInjector.java:135) ~[na:0.0]
            at com.app.GCMIntentService.parseMessage(GCMIntentService.java:149) ~[na:0.0]
            at com.app.GCMIntentService.onMessage(GCMIntentService.java:138) ~[na:0.0]
            at com.app.GCMIntentService.onHandleIntent(GCMIntentService.java:95) ~[na:0.0]
            at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65) ~[na:0.0]
            at android.os.Handler.dispatchMessage(Handler.java:99) ~[na:0.0]
            at android.os.Looper.loop(Looper.java:137) ~[na:0.0]
            at android.os.HandlerThread.run(HandlerThread.java:60) ~[na:0.0]
```

**Comment by supoved** [comment]
+1 I have got the similar issue

**Comment by supoved** [comment]
Just have found the reason and the workaround.

If none of your classes injects it through Inject annotation, then it wont be listed in the mappings, and getInstance will fail.

@ahmednasir91 try this as workaround:

```
public class SomeClass {
    @Inject @Named("BOOKING") GCMMessage bookingGcmMessage;
}
```

**Comment by ahmednasir91** [comment]
@supoved sure will try it out.
