### ISSUE TITLE
Crash when trying to use DatePickerDialog

### ISSUE THREAD

**Issue by clementhely** [roboguice/roboguice#314]
Hello,

My application uses Roboguice (version 3.0-alpha-2, at the moment) and I recently discovered a crash that happens quite rarely, when instantiating a DatePickerDialog in a RoboActionBarActivity, or a RoboFragment.

The only device I own which can reproduce the problem is a Nexus 9 with Android M Preview. But I recently had two users mentioning a similar issue, one of them with Android M Preview as well, but the other has a Galaxy S6 with Android 5.0.2.

When creating a DatePickerDialog with:
```java
DatePickerDialog dpd = new DatePickerDialog(getActivity(), this, calendar.get(Calendar.YEAR), calendar.get(Calendar.MONTH), calendar.get(Calendar.DAY_OF_MONTH));
```
... here is the stacktrace I see:

```
Caused by: java.lang.RuntimeException: java.lang.IllegalAccessException: java.lang.Class<android.widget.DayPickerView> is not accessible from java.lang.Class<roboguice.activity.RoboActivity>
            at roboguice.activity.RoboActivity.injectOnCreateView(RoboActivity.java:205)
            at roboguice.activity.RoboActionBarActivity.onCreateView(RoboActionBarActivity.java:178)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:748)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
            at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
            at android.view.LayoutInflater.parseInclude(LayoutInflater.java:971)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:831)
            at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
            at android.widget.DatePickerCalendarDelegate.<init>(DatePickerCalendarDelegate.java:118)
            at android.widget.DatePicker.createCalendarUIDelegate(DatePicker.java:160)
            at android.widget.DatePicker.<init>(DatePicker.java:140)
            at android.widget.DatePicker.<init>(DatePicker.java:126)
            at android.widget.DatePicker.<init>(DatePicker.java:122)
            at java.lang.reflect.Constructor.newInstance(Native Method)
            at android.view.LayoutInflater.createView(LayoutInflater.java:619)
            at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
            at android.view.LayoutInflater.onCreateView(LayoutInflater.java:694)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:762)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
            at android.app.DatePickerDialog.<init>(DatePickerDialog.java:112)
            at android.app.DatePickerDialog.<init>(DatePickerDialog.java:82)
```

The rest of the stacktrace is just several InflateExceptions, bubbling all the way up to DatePicker, through DayPickerView.

I dug a bit into DatePickerDialog code, but I didn't really manage to understand what the best approach was to solve this crash. It seems the Context provided as the first parameter of DatePickerDialog constructor will be used to create the DayPickerView, which is a package private class. And of course, using the application's Context will not work for a dialog.

What is quite surprising, though, is that in a huge majority of cases (hundreds of different devices and many different versions of Android, starting at API 14) this DatePickerDialog doesn't cause any problem. So far only these 2 users reported the issue, and I only manage to reproduce it on a Nexus 9 with Android M Preview. Would it not be meant to crash on every single version of Android and any single device, as the Context use is always outside of android.widget package?

Has anyone experienced a similar issue or have any clue on how to solve it?

Thank you in advance!

**Comment by Marcellsantoso** [comment]
Has this issue being resolved? or do you have any way to fix it? @clementhely

**Comment by clementhely** [comment]
To solve it, we basically changed our activity to extend `ActionBarActivity` and to implement `RoboContext`, instead of simply extending `RoboActionBarActivity`. This means we had to replicate the lifecycle and injection logic from `RoboActionBarActivity`, removing the lines responsible for the crash.

Did that a while ago, so I'm not exactly sure what the logic behind it was, but after investigating, we figured that the crash was happening because of these lines, in the `onCreateView()` methods:
```java
if (RoboActivity.shouldInjectOnCreateView(name))
            return RoboActivity.injectOnCreateView(name, context, attrs);
```
So creating our own activity class, without these two calls to `RoboActivity.injectOnCreateView(name, context, attrs)` solved the problem. I think this is because `shouldInjectOnCreateView(String)` was checking if the name contained a package name, and if the package name wasn't starting by `com.android`. But looking at [this commit](https://github.com/roboguice/roboguice/commit/de951748d2e68779c88bae1d7ef88b4e5e139f89), it seems that this behaviour changed in Roboguice 3.0 (at the time we were using 3.0.0-alpha2), so it's possible that this issue is not happening anymore, otherwise you can create your own activity class, removing the calls to `RoboActivity.injectOnCreateView`, as we did.

**Comment by Marcellsantoso** [comment]
So i've been using roboguice version 2+.. Once i changed it to version 3, it's working fine.
Thanks for your help! :) @clementhely

**Comment by jon-adams** [comment]
RoboGuice 3.0 did indeed change `RoboActivity.shouldInjectOnCreateView` to always return `false` to "fix" this. However, then you don't get view injection in some cases. 

I prefer to instead replace `RoboActivity` with the same one as RoboGuice 3 except I leave the RoboGuice 2 `shouldInjectOnCreateView` method the way it was. To get around the original crash though, I add additional filters as I come across them. Example:

```
protected static boolean shouldInjectOnCreateView(final String name) {
     // RoboGuice 3 implementation
     // return false; // boo! lazy fix

     // original RoboGuice 2 implementation
     return Character.isLowerCase(name.charAt(0)) && !name.startsWith("com.android") 
            && !name.equals("fragment")
            // this is an additional namespace I've added to this logic filter
            && !name.startsWith("android.widget");
}
```
