### ISSUE TITLE
With some devices com.google.inject is unable to resolve

### ISSUE THREAD

**Issue by rickytribbia** [roboguice/roboguice#323]
Hi all, 
thank you for all, we love Roboguice, really. 

This time we can't make it works, and we don't know why. 

Simple gradle configuration into our AndroidStudio project of a simple Android app: 

```
compile 'org.roboguice:roboguice:3.0.1'
provided 'org.roboguice:roboblender:3.0.1'
```

It works for a lot of smartphones (Nexus 5, Samsung S5, S6, etc.). Obviously our customer hasn't these ones, but a Samsung Galaxy Ace 4 (Android 4.4): our app crashes at loading time: 

```
09-10 12:33:27.043  27193-27193/--our-app-package E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: --our-app-package, PID: 27193
    java.lang.NoClassDefFoundError: com.google.inject.Stage
            at roboguice.RoboGuice.<clinit>(RoboGuice.java:53)
            at roboguice.activity.RoboActivity.onCreate(RoboActivity.java:90)
            at --our-app-package.activities.BaseActivity.onCreate(BaseActivity.java:34)
            at --our-app-package.activities.SplashscreenActivity.onCreate(SplashscreenActivity.java:61)
            at android.app.Activity.performCreate(Activity.java:5296)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2283)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2370)
            at android.app.ActivityThread.access$800(ActivityThread.java:155)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1243)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5426)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
            at dalvik.system.NativeStart.main(Native Method)
```
(entire crash log as attachment: 
![github_crash_log](https://cloud.githubusercontent.com/assets/1375266/9852121/c7ce4d4c-5afc-11e5-8081-90f1b0c3a255.png) )

So we try to add additional support of "com.google.inject" from Guice (3.0_no-aop) but obviously we encountered the 

```
Error:Execution failed for task ':app:packageAllDebugClassesForMultiDex'.
> java.util.zip.ZipException: duplicate entry: com/google/inject/AbstractModule.class
```

at compile time. 

The problem is duplicable with Genymotion with "Custom Phone 4.4.4 API 19 768x1280" virtual device. 

Any suggestion?

Thank you in advance

**Comment by ibamadd** [comment]
@rickytribbia were you able to figure this out?

**Comment by rickytribbia** [comment]
Yes, I fix it changing ```multiDexEnabled``` from ```true``` to ```false``` and choosing only used google-play-services libraries. 

This option caused the error related to this issue and other ones which at first time seemed linked to roboguice but they were not.

**Comment by ibamadd** [comment]
I need `multiDexEnabled` for other libs so I can't set it to `false`. Thanks for your reply.

Do you think this will be addressed in the new version @stephanenicolas ?

**Comment by ShanePhelan** [comment]
I had the same issue (and also needed multiDexEnabled) and fixed it by using the multi dex support library for older devices:

1. add 'com.android.support:multidex:1.0.1' to your gradle compile options
2. If you're extending the android.app.Application override the attachBaseContext method
`@Override
	protected void attachBaseContext(Context base) {
		super.attachBaseContext(base);
		MultiDex.install(this);
	}`
3. If you're not extending then you need to add the MultiDexApplication to your manifest application:
`android:name="android.support.multidex.MultiDexApplication"`

See here for more details [MultiDex](http://developer.android.com/tools/building/multidex.html)

Hope this helps someone as it had me stumped for a while!

**Comment by rickytribbia** [comment]
Great solution!
:+1:
