### ISSUE TITLE
Getting java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by EfthimisCharitonidis** [roboguice/roboguice#328]
Here's the crash report:

java.lang.NoClassDefFoundError: roboguice.inject.ContextScopedRoboInjector
	at roboguice.RoboGuice.getInjector(RoboGuice.java:197)
	at com.grekomania.activity.MainActivity.onCreate(MainActivity.java:626)
	at android.app.Activity.performCreate(Activity.java:5193)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2189)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2286)
	at android.app.ActivityThread.access$600(ActivityThread.java:144)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1259)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5166)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:561)
	at dalvik.system.NativeStart.main(Native Method)

and the onCreate() method

    @Override
    protected void onCreate(Bundle savedInstanceState) {

        final RoboInjector injector = RoboGuice.getInjector(this);
        eventManager = injector.getInstance(EventManager.class);
        injector.injectMembersWithoutViews(this);

        super.onCreate(savedInstanceState);
        eventManager.fire(new OnCreateEvent<Activity>(this, savedInstanceState));

        setContentView(R.layout.activity_main);
...
...
}

On some devices the app runs smoothly on some other it crashes with such error

**Comment by RohanSakhale** [comment]
I am also getting the same error, below is the stacktrace

```
java.lang.NoClassDefFoundError: roboguice.inject.ContextScopedRoboInjector
    at roboguice.RoboGuice.getInjector(RoboGuice.java:197)
    at roboguice.activity.RoboActivity.onCreate(RoboActivity.java:90)
    at com.bnmcombines.galleryflavors.Launcher.onCreate(Launcher.java:71)
    at android.app.Activity.performCreate(Activity.java:5343)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2343)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2441)
    at android.app.ActivityThread.access$900(ActivityThread.java:151)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
    at android.os.Handler.dispatchMessage(Handler.java:110)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:5345)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644)
    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by marco-manza** [comment]
Same error here, API 18
