### ISSUE TITLE
java.lang.IllegalStateException: Unable to use annotation database(s)

### ISSUE THREAD

**Issue by micsay** [roboguice/roboguice#344]
Hi,
when I install verson 3.0.1 ,it giving this exception.

 FATAL EXCEPTION: main
                                                                         Process: com.example.mmy_pc.qrcode, PID: 3413
                                                                         java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.mmy_pc.qrcode/com.example.mmy_pc.qrcode.MainActivity}: java.lang.IllegalStateException: Unable to use annotation database(s)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
                                                                             at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:136)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:515)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                                             at dalvik.system.NativeStart.main(Native Method)
                                                                          Caused by: java.lang.IllegalStateException: Unable to use annotation database(s)
                                                                             at roboguice.RoboGuice.initializeAnnotationDatabaseFinderAndHierarchyTraversalFilterFactory(RoboGuice.java:292)
                                                                             at roboguice.RoboGuice.getOrCreateBaseApplicationInjector(RoboGuice.java:149)
                                                                             at roboguice.RoboGuice.getOrCreateBaseApplicationInjector(RoboGuice.java:90)
                                                                             at roboguice.RoboGuice.getInjector(RoboGuice.java:197)
                                                                             at roboguice.activity.RoboActivity.onCreate(RoboActivity.java:90)
                                                                             at com.example.mmy_pc.qrcode.MainActivity.onCreate(MainActivity.java:11)
                                                                             at android.app.Activity.performCreate(Activity.java:5231)
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
                                                                             at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:136) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5017) 
                                                                             at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                             at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                                             at dalvik.system.NativeStart.main(Native Method) 
                                                                          Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: AnnotationDatabaseImpl
                                                                             at com.google.inject.AnnotationDatabaseFinder.<init>(AnnotationDatabaseFinder.java:47)
                                                                             at com.google.inject.Guice.setAnnotationDatabasePackageNames(Guice.java:133)
                                                                             at roboguice.RoboGuice.initializeAnnotationDatabaseFinderAndHierarchyTraversalFilterFactory(RoboGuice.java:288)
                                                                             at roboguice.RoboGuice.getOrCreateBaseApplicationInjector(RoboGuice.java:149) 
                                                                             at roboguice.RoboGuice.getOrCreateBaseApplicationInjector(RoboGuice.java:90) 
                                                                             at roboguice.RoboGuice.getInjector(RoboGuice.java:197) 
                                                                             at roboguice.activity.RoboActivity.onCreate(RoboActivity.java:90) 
                                                                             at com.example.mmy_pc.qrcode.MainActivity.onCreate(MainActivity.java:11) 
                                                                             at android.app.Activity.performCreate(Activity.java:5231) 
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159) 
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
                                                                             at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:136) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5017) 
                                                                             at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                             at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                                             at dalvik.system.NativeStart.main(Native Method) 
                                                                          Caused by: java.lang.ClassNotFoundException: AnnotationDatabaseImpl
                                                                             at java.lang.Class.classForName(Native Method)
                                                                             at java.lang.Class.forName(Class.java:251)
                                                                             at java.lang.Class.forName(Class.java:216)
                                                                             at com.google.inject.AnnotationDatabaseFinder.getAnnotationDatabaseInstance(AnnotationDatabaseFinder.java:73)
                                                                             at com.google.inject.AnnotationDatabaseFinder.<init>(AnnotationDatabaseFinder.java:36)
                                                                             at com.google.inject.Guice.setAnnotationDatabasePackageNames(Guice.java:133) 
                                                                             at roboguice.RoboGuice.initializeAnnotationDatabaseFinderAndHierarchyTraversalFilterFactory(RoboGuice.java:288) 
                                                                             at roboguice.RoboGuice.getOrCreateBaseApplicationInjector(RoboGuice.java:149) 
                                                                             at roboguice.RoboGuice.getOrCreateBaseApplicationInjector(RoboGuice.java:90) 
                                                                             at roboguice.RoboGuice.getInjector(RoboGuice.java:197) 
                                                                             at roboguice.activity.RoboActivity.onCreate(RoboActivity.java:90) 
                                                                             at com.example.mmy_pc.qrcode.MainActivity.onCreate(MainActivity.java:11) 
                                                                             at android.app.Activity.performCreate(Activity.java:5231) 
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159) 
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
                                                                             at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:136) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5017) 
                                                                             at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                             at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                                             at dalvik.system.NativeStart.main(Native Method) 
                                                                          Caused by: java.lang.NoClassDefFoundError: AnnotationDatabaseImpl
                                                                             at java.lang.Class.classForName(Native Method) 
                                                                             at java.lang.Class.forName(Class.java:251) 
                                                                             at java.lang.Class.forName(Class.java:216) 
                                                                             at com.google.inject.AnnotationDatabaseFinder.getAnnotationDatabaseInstance(AnnotationDatabaseFinder.java:73) 
                                                                             at com.google.inject.AnnotationDatabaseFinder.<init>(AnnotationDatabaseFinder.java:36) 
                                                                             at com.google.inject.Guice.setAnnotationDatabasePackageNames(Guice.java:133) 
                                                                             at roboguice.RoboGuice.initializeAnnotationDatabaseFinderAndHierarchyTraversalFilterFactory(RoboGuice.java:288) 
                                                                             at roboguice.RoboGuice.getOrCreateBaseApplicationInjector(RoboGuice.java:149) 
                                                                             at roboguice.RoboGuice.getOrCreateBaseApplicationInjector(RoboGuice.java:90) 
                                                                             at roboguice.RoboGuice.getInjector(RoboGuice.java:197) 
                                                                             at roboguice.activity.RoboActivity.onCreate(RoboActivity.java:90) 
                                                                             at com.example.mmy_pc.qrcode.MainActivity.onCreate(MainActivity.java:11) 
                                                                             at android.app.Activity.performCreate(Activity.java:5231) 
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159) 
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
                                                                             at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:136) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5017) 
                                                                             at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                             at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                                             at dalvik.system.NativeStart.main(Native Method) 
                                                                          Caused by: java.lang.ClassNotFoundException: Didn't find class "AnnotationDatabaseImpl" on path: DexPathList[[zip file "/data/app/com.example.mmy_pc.qrcode-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.example.mmy_pc.qrcode-2, /vendor/lib, /system/lib]]
                                                                             at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                                             at java.lang.Class.classForName(Native Method) 
                                                                             at java.lang.Class.forName(Class.java:251) 
                                                                             at java.lang.Class.forName(Class.java:216) 
                                                                             at com.google.inject.AnnotationDatabaseFinder.getAnnotationDatabaseInstance(AnnotationDatabaseFinder.java:73) 
                                                                             at com.google.inject.AnnotationDatabaseFinder.<init>(AnnotationDatabaseFinder.java:36) 
                                                                             at com.google.inject.Guice.setAnnotationDatabasePackageNames(Guice.java:133) 
                                                                             at roboguice.RoboGuice.initializeAnnotationDatabaseFinderAndHierarchyTraversalFilterFactory(RoboGuice.java:288) 
                                                                             at roboguice.RoboGuice.getOrCreateBaseApplicationInjector(RoboGuice.java:149) 
                                                                             at roboguice.RoboGuice.getOrCreateBaseApplicationInjector(RoboGuice.java:90) 
                                                                             at roboguice.RoboGuice.getInjector(RoboGuice.java:197) 
                                                                             at roboguice.activity.RoboActivity.onCreate(RoboActivity.java:90) 
                                                                             at com.example.mmy_pc.qrcode.MainActivity.onCreate(MainActivity.java:11) 
                                                                             at android.app.Activity.performCreate(Activity.java:5231) 
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159) 
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
                                                                             at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:136) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5017) 
                                                                             at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                             at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                                             at dalvik.system.NativeStart.main(Native Method)

Thank you for your help.

**Comment by micsay** [comment]
I spend lots of time in this exception ,but still wrong

**Comment by UNCVR** [comment]
Try to add :
`gradle.projectsEvaluated {
  tasks.withType(JavaCompile) {
            options.compilerArgs << "-AguiceAnnotationDatabasePackageName=com.android.app.sample"
        }
    }`
in your build.gradle file at project level

**Comment by hfutzhu** [comment]
same problem!how to  resolve

**Comment by 2ndGAB** [comment]
Hello,

I'm just facing the same problem (I think) with Android Studio 3.

    E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.me.service.headersample, PID: 10118
                  java.lang.RuntimeException: Unable to create application com.me.service.samples.App: java.lang.IllegalStateException: Unable to use annotation database(s)
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5406)
                      at android.app.ActivityThread.-wrap2(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                   Caused by: java.lang.IllegalStateException: Unable to use annotation database(s)
                      at roboguice.RoboGuice.initializeAnnotationDatabaseFinderAndHierarchyTraversalFilterFactory(RoboGuice.java:292)
                      at roboguice.RoboGuice.getOrCreateBaseApplicationInjector(RoboGuice.java:113)
                      at com.me.service.samples.App.onCreate(App.java:18)
                      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
                      at android.app.ActivityThread.-wrap2(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:154) 
                      at android.app.ActivityThread.main(ActivityThread.java:6119) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
                   Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: AnnotationDatabaseImpl
                      at com.google.inject.AnnotationDatabaseFinder.<init>(AnnotationDatabaseFinder.java:47)
                      at com.google.inject.Guice.setAnnotationDatabasePackageNames(Guice.java:133)
                      at roboguice.RoboGuice.initializeAnnotationDatabaseFinderAndHierarchyTraversalFilterFactory(RoboGuice.java:288)
                      at roboguice.RoboGuice.getOrCreateBaseApplicationInjector(RoboGuice.java:113) 
                      at com.me.service.samples.App.onCreate(App.java:18) 
                      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024) 
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403) 
                      at android.app.ActivityThread.-wrap2(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:154) 
                      at android.app.ActivityThread.main(ActivityThread.java:6119) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
                   Caused by: java.lang.ClassNotFoundException: AnnotationDatabaseImpl
                      at java.lang.Class.classForName(Native Method)
                      at java.lang.Class.forName(Class.java:400)
                      at java.lang.Class.forName(Class.java:326)
                      at com.google.inject.AnnotationDatabaseFinder.getAnnotationDatabaseInstance(AnnotationDatabaseFinder.java:73)
                      at com.google.inject.AnnotationDatabaseFinder.<init>(AnnotationDatabaseFinder.java:36)
                      at com.google.inject.Guice.setAnnotationDatabasePackageNames(Guice.java:133) 
                      at roboguice.RoboGuice.initializeAnnotationDatabaseFinderAndHierarchyTraversalFilterFactory(RoboGuice.java:288) 
                      at roboguice.RoboGuice.getOrCreateBaseApplicationInjector(RoboGuice.java:113) 
                      at com.me.service.samples.App.onCreate(App.java:18) 
                      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024) 
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403) 
                      at android.app.ActivityThread.-wrap2(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:154) 
                      at android.app.ActivityThread.main(ActivityThread.java:6119) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
                   Caused by: java.lang.ClassNotFoundException: Didn't find class "AnnotationDatabaseImpl" on path: DexPathList[[zip file "/data/app/com.me.service.headersample-2/base.apk"],nativeLibraryDirectories=[/data/app/com.me.service.headersample-2/lib/x86, /system/lib, /vendor/lib]]
                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                      at java.lang.Class.classForName(Native Method) 
                      at java.lang.Class.forName(Class.java:400) 
                      at java.lang.Class.forName(Class.java:326) 
                      at com.google.inject.AnnotationDatabaseFinder.getAnnotationDatabaseInstance(AnnotationDatabaseFinder.java:73) 
                      at com.google.inject.AnnotationDatabaseFinder.<init>(AnnotationDatabaseFinder.java:36) 
                      at com.google.inject.Guice.setAnnotationDatabasePackageNames(Guice.java:133) 
                      at roboguice.RoboGuice.initializeAnnotationDatabaseFinderAndHierarchyTraversalFilterFactory(RoboGuice.java:288) 
                      at roboguice.RoboGuice.getOrCreateBaseApplicationInjector(RoboGuice.java:113) 
                      at com.me.service.samples.App.onCreate(App.java:18) 
                      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024) 
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403) 
                      at android.app.ActivityThread.-wrap2(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:154) 
                      at android.app.ActivityThread.main(ActivityThread.java:6119) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 

Works well in Android Studio 2.3.3

Any idea??
